/* ===================================================================
   Safety Dance — Inspect AI Adapter
   Converts an Inspect AI task descriptor into a Safety Dance benchmark
   manifest. Since Inspect tasks are defined in Python, this adapter
   works with a JSON task descriptor — either serialized from Python
   via introspection or hand-written to describe the task's capabilities.

   See: https://github.com/UKGovernmentBEIS/inspect_ai
   =================================================================== */

/**
 * Scorer type → measurement type mapping.
 */
const SCORER_TO_MEASUREMENT = {
  choice: 'binary',
  match: 'binary',
  exact: 'binary',
  includes: 'binary',
  pattern: 'binary',
  answer: 'binary',
  f1: 'scalar',
  math: 'scalar',
  model_graded_qa: 'rubric',
  model_graded_fact: 'rubric',
};

/**
 * Derive a Safety Dance BenchmarkManifest from an Inspect AI task descriptor.
 *
 * The descriptor captures the relevant metadata from a Python Task object.
 * It can be generated by introspecting a @task function or written manually.
 *
 * @param {Object} descriptor - Inspect task descriptor
 * @param {string} descriptor.name              - Task name (from @task function name)
 * @param {string} [descriptor.display_name]     - Human-readable name
 * @param {string} [descriptor.description]      - What the task evaluates
 * @param {number} [descriptor.version]          - Task version
 * @param {string[]} [descriptor.tags]           - Eval-time labels
 * @param {Object} [descriptor.metadata]         - Arbitrary metadata
 *
 * @param {Object} [descriptor.solver]           - Solver configuration
 * @param {string} descriptor.solver.type        - 'generate' | 'chain_of_thought' | 'basic_agent' | 'custom'
 * @param {string[]} [descriptor.solver.tools]   - Tool names: 'bash', 'python', 'web_browser', etc.
 * @param {boolean} [descriptor.solver.has_system_message] - Whether solver sets a system message
 *
 * @param {Object} [descriptor.scorer]           - Scorer configuration
 * @param {string} descriptor.scorer.type        - Scorer name: 'choice', 'match', 'f1', 'model_graded_qa', etc.
 *
 * @param {Object} [descriptor.dataset]          - Dataset info
 * @param {string[]} [descriptor.dataset.modalities] - Input modalities present: 'text', 'image', 'audio'
 * @param {number} [descriptor.dataset.sample_count] - Number of samples
 *
 * @param {string|null} [descriptor.sandbox]     - Sandbox type: 'docker', 'k8s', null
 * @param {number|null} [descriptor.message_limit] - Max messages per sample
 * @param {number|null} [descriptor.token_limit]   - Max tokens per sample
 * @param {number|null} [descriptor.time_limit]    - Seconds time limit
 * @param {number|null} [descriptor.epochs]        - Repeated runs per sample
 * @param {Object} [descriptor.config]             - GenerateConfig
 * @param {number} [descriptor.config.max_tokens]  - Max output tokens
 *
 * @returns {Object} BenchmarkManifest
 */
export function taskToManifest(descriptor) {
  const solver = descriptor.solver || {};
  const scorer = descriptor.scorer || {};
  const dataset = descriptor.dataset || {};
  const config = descriptor.config || {};

  // ── Interaction Pattern ──
  const agentTypes = ['basic_agent', 'agent'];
  const isAgentic = agentTypes.includes(solver.type);
  const hasTools = !!(solver.tools && solver.tools.length > 0);
  const isMultiTurn = isAgentic || (hasTools && descriptor.message_limit > 1);
  const pattern = isAgentic ? 'agentic' : (isMultiTurn ? 'multi_turn' : 'single_turn');

  // ── Input Modalities ──
  const inputModalities = dataset.modalities || ['text'];

  // ── Output Modalities ──
  const outputModalities = ['text'];
  if (hasTools || isAgentic) {
    outputModalities.push('tool_use');
  }
  if (config.response_format || descriptor.structured_output) {
    if (!outputModalities.includes('structured_json')) {
      outputModalities.push('structured_json');
    }
  }
  if (descriptor.sandbox && (solver.tools || []).some(t =>
    ['bash', 'python', 'bash_session', 'code_execution'].includes(t))) {
    if (!outputModalities.includes('code_execution')) {
      outputModalities.push('code_execution');
    }
  }

  // ── Resources ──
  const resources = {};
  if (descriptor.token_limit) {
    resources.min_context_tokens = descriptor.token_limit;
  }
  if (config.max_tokens) {
    resources.min_output_tokens = config.max_tokens;
  }
  if (hasTools) {
    resources.tool_count = solver.tools.length;
  }

  // ── Measurement ──
  const measurement = {};
  if (scorer.type) {
    measurement.type = SCORER_TO_MEASUREMENT[scorer.type] || 'scalar';
  }

  // ── Safety Domains ──
  const domains = inferSafetyDomains(descriptor);

  const manifest = {
    manifest_version: '0.1.0',
    id: `inspect/${descriptor.name}`,
    label: descriptor.display_name || descriptor.name,
    description: descriptor.description || '',
    source: 'inspect',
    interaction: {
      pattern,
      timing: 'untimed',
    },
    input: {
      modalities: inputModalities,
      system_prompt: !!(solver.has_system_message),
    },
    output: {
      modalities: outputModalities,
    },
    resources,
    safety: {
      domain: domains,
    },
    measurement,
    metadata: {
      inspect_solver_type: solver.type || null,
      inspect_scorer_type: scorer.type || null,
      inspect_sandbox: descriptor.sandbox || null,
      inspect_epochs: descriptor.epochs || null,
      inspect_version: descriptor.version || null,
      inspect_tags: descriptor.tags || [],
      ...(descriptor.metadata || {}),
    },
  };

  // Conditional fields
  if (descriptor.message_limit) {
    manifest.interaction.max_turns = descriptor.message_limit;
  }
  if (descriptor.time_limit) {
    manifest.interaction.time_limit_ms = descriptor.time_limit * 1000;
  }

  return manifest;
}

/**
 * Convert an array of Inspect task descriptors into manifests.
 *
 * @param {Object[]} descriptors
 * @returns {Object[]}
 */
export function allTasksToManifests(descriptors) {
  return descriptors.map(d => taskToManifest(d));
}

/**
 * Infer safety domains from task descriptor metadata, tags, and name.
 * @param {Object} descriptor
 * @returns {string[]}
 */
function inferSafetyDomains(descriptor) {
  const domains = new Set();
  const name = (descriptor.name || '').toLowerCase();
  const desc = (descriptor.description || '').toLowerCase();
  const tags = (descriptor.tags || []).map(t => t.toLowerCase());
  const allText = [name, desc, ...tags].join(' ');

  if (allText.includes('cyber') || allText.includes('ctf') || allText.includes('exploit')) {
    domains.add('cyber_operations');
  }
  if (allText.includes('harm') || allText.includes('toxic') || allText.includes('safety')) {
    domains.add('civilian_harm');
  }
  if (allText.includes('decept') || allText.includes('misinform') || allText.includes('persuad')) {
    domains.add('deception');
  }
  if (allText.includes('weapon') || allText.includes('nuclear') || allText.includes('chemical')) {
    domains.add('weapons_of_mass_destruction');
  }
  if (allText.includes('financ') || allText.includes('fraud') || allText.includes('money')) {
    domains.add('financial_manipulation');
  }
  if (allText.includes('surveil') || allText.includes('privacy') || allText.includes('monitor')) {
    domains.add('surveillance');
  }

  // Check explicit safety_dance metadata
  if (descriptor.metadata?.safety_dance?.safety_domain) {
    for (const d of descriptor.metadata.safety_dance.safety_domain) {
      domains.add(d);
    }
  }

  return [...domains];
}
